runtime: nodejs20

instance_class: F1

env_variables:
  BUCKET_NAME: "example-gcs-bucket"
  MESSAGE_STYLE: "uppercase"

handlers:
- url: /public
  static_dir: public

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
 